// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lunsdnibwhborkgsvwwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1bnNkbmlid2hib3JrZ3N2d3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjkyNTgsImV4cCI6MjA2NDg0NTI1OH0.8YAC-evq0KXQH9yEf4B2qD6XT0fLqRIOA-V4UjLCm9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);